# -*- coding: utf-8 -*-
{
    'name': "marketplace_security",

    'summary': """
        Configuración de seguridad
""",

    'description': """
        Configuraciones de seguridad
    """,

    'author': "Pablo Manule Rizzo",
    'website': "http://pablorizzo.com",

    # Categories can be used to filter modules in modules listing
    # Check https://github.com/odoo/odoo/blob/14.0/odoo/addons/base/data/ir_module_category_data.xml
    # for the full list
    'category': 'Sales',
    'version': '0.1',
    'installable': True,
    'application': True,
    

    # any module necessary for this one to work correctly
    'depends': ['sale_management',
'account',
'website',
'stock',
'purchase',
'website_sale',
'mass_mailing',
'sign',
'sale_subscription',
'mail',
'contacts',
'social',
'marketing_automation',
'payment_paypal',
'l10n_latam_base',
'stock_account',
'website_sms',
'website_sale_dashboard',
'purchase_stock',
'account_debit_note',
'account_edi',
'account_edi_facturx',
'account_edi_ubl',
'account_invoice_extract',
'account_invoice_extract_purchase',
'account_online_sync',
'account_online_synchronization',
'account_payment',
'account_plaid',
'account_ponto',
'account_yodlee',
'analytic',
'analytic_enterprise',
'attachment_indexation',
'auth_signup',
'auth_totp',
'auth_totp_portal',
'barcodes',
'barcodes_mobile',
'base',
'base_automation',
'base_geolocalize',
'base_import',
'base_setup',
'base_vat',
'bus',
'contacts_enterprise',
'coupon',
'currency_rate_live',
'digest',
'digest_enterprise',
'fetchmail',
'google_recaptcha',
'iap',
'iap_mail',
'l10n_ar',
'l10n_latam_invoice_document',
'link_tracker',
'mail_bot',
'mail_enterprise',
'mail_mobile',
'mass_mailing_sale',
'partner_autocomplete',
'payment',
'payment_fix_register_token',
'payment_transfer',
'portal_rating',
'procurement_jit',
'product',
'product_expiry',
'purchase_enterprise',
'purchase_stock_enterprise',
'rating',
'resource',
'sale',
'sale_coupon',
'sale_enterprise',
'sale_margin',
'sale_product_configurator',
'sale_purchase',
'sale_purchase_stock',
'sale_stock',
'sale_stock_margin',
'sale_subscription_dashboard',
'sales_team',
'sms',
'snailmail',
'snailmail_account',
'social_facebook',
'social_linkedin',
'social_media',
'social_push_notifications',
'social_sale',
'social_twitter',
'stock_account_enterprise',
'stock_enterprise',
'stock_sms',
'uom',
'utm',
'web',
'web_cohort',
'web_dashboard',
'web_editor',
'web_enterprise',
'web_gantt',
'web_grid',
'web_kanban_gauge',
'web_map',
'web_mobile',
'web_tour',
'web_unsplash',
'website_enterprise',
'website_form',
'website_links',
'website_mail',
'website_mass_mailing',
'website_payment',
'website_sale_comparison',
'website_sale_coupon',
'website_sale_management',
'website_sale_product_configurator',
'website_sale_stock',
'website_sale_stock_product_configurator',
'website_sale_wishlist',
'mass_mailing_themes',
'portal',
'http_routing',
'phone_validation',
],

    # always loaded
    'data': [
        'security/res.groups.csv',
        'security/multi-company.xml',
        #'security/ir.model.access.csv',
        # 'security/ir.model.access.csv',
        #'views/views.xml',
        #'views/templates.xml',
    ],
    # only loaded in demonstration mode
    'demo': [
        #'demo/demo.xml',
    ],
}
